# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  schedule:
    - cron: '30 15 * * *'  # every day at midnight

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout private data file
      uses: actions/checkout@v2
      with:
        repository: wonderwater/my_data
        token: ${{ secrets.token }}
        path: tmp
    - run: mv tmp/leetcode/db .
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - env: 
        cookie: ${{ secrets.cookie }}
      run: java -jar target/*dependencies.jar
    - run: mkdir staging && cp db staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
    - uses: EndBug/add-and-commit@v7
      with:
        message: 'update README.md'
        add: 'README.md --force'
    - run: |
        git config --global user.email "any@water.com"
        git config --global user.name "github-action"
        mv db tmp/leetcode/
        cd tmp && git add * && git commit -m "commit" && git push

